### ISSUE TITLE
Incompatibility with ruby 1.9.2

### ISSUE THREAD

**Issue by tretkow** [rejeep/authlogic-password-reset-tutorial#1]
Constructions like this 

```
request_new = lambda do
  get :new
end
```

cannot be passed as a block to instance_eval on ruby 1.9.2, otherwise "ArgumentError: wrong number of arguments (1 for 0)" is raised.

This can be fixed by replacing 'lambda" with 'proc'.
## 

Adam Tretkowski
ruby -v
ruby 1.9.2dev (2010-06-25 revision 28427) [i686-linux]

**Comment by rejeep** [comment]
Really?

Can you give me a working example of that? This code for example works for me in both 1.9.2 and 1.8.7.

```
class C
  @@contexts = []

  def self.context(&block)
    @@contexts << block
  end

  common = lambda do
    puts 'Some common stuff here...'
  end

  context &common
end

C.send(:class_variable_get, '@@contexts').each do |context|
  context.call
end
```

**Comment by tretkow** [comment]
```
some_lambda = lambda do 
    puts "Lambda is printing..."
end

class SomeClass
    def self.use_lambda(&block)
        instance_eval(&block)
    end
end

SomeClass.use_lambda &some_lambda


tretkow@ufo-desk:~/devel/lambda$ ruby -v
ruby 1.8.7 (2009-06-12 patchlevel 174) [i686-linux]
tretkow@ufo-desk:~/devel/lambda$ ruby example.rb 
Lambda is printing...
tretkow@ufo-desk:~/devel/lambda$ rvm 1.9.2-head
tretkow@ufo-desk:~/devel/lambda$ ruby -v
ruby 1.9.2dev (2010-06-25 revision 28427) [i686-linux]
tretkow@ufo-desk:~/devel/lambda$ ruby example.rb 
example.rb:2:in `block in <main>': wrong number of arguments (1 for 0)   (ArgumentError)
from example.rb:7:in `instance_eval'
from example.rb:7:in `use_lambda'
from example.rb:11:in `<main>'
```

**Comment by rejeep** [comment]
Thanks!

http://github.com/rejeep/authlogic-password-reset-tutorial/commit/db613f607a8dd40cbb0718ed6b9cfbdcd1b8f72f
